name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout V
        uses: actions/checkout@v4
        with:
          repository: vlang/v

      - name: Checkout vorum
        uses: actions/checkout@v2
        with:
          path: vorum

      - name: Build V
        run: make && ./v symlink

      - name: Build Vorum
        run: v vorum

      - name: Check Vorum code is VFMTed
        run: v fmt -verify vorum/

      - name: Vet Vorum
        run: v vet vorum
